ARG TARGETARCH
ARG VER=app-opensuse-15.6
FROM registry.cn-shenzhen.aliyuncs.com/infrastlabs/x11-base:${VER}
RUN \
  echo a.1234; \
  # avoid: apt ins pulseaudio's replaceConfirm
  rm -f /etc/pulse/default.pa; \
  zyp.sh \
  xorg-x11-server \
  # xserver-xorg-video-all \
  xf86-input-evdev xf86-video-amdgpu xf86-video-intel xf86-video-dummy
  

RUN \
# lame sox libsox-fmt-mp3
  # Problem: 1: the installed wireplumber-audio-0.5.2-150600.1.2.noarch conflicts with 'pulseaudio' provided by the to be installed pulseaudio-17.0-150600.2.3.x86_64
  zyp.sh pulseaudio; \
  zyp.sh \
  # lame existed.
  # sox: play xx.mp3; alsa: aplay -l
  lame sox \
  # none: beep dbus-x11 libsox-fmt-mp3 \
  # alsa-oss alsa-tools-gui alsamixergui \
  alsa-tools alsa-utils mpg123 ; \
  echo "curl mp3.." && su - headless -c "curl --connect-timeout 3 -k -O -fSL https://downsc.chinaz.net/files/download/sound1/201309/3476.mp3";
